<div class="row">
    <div class="col-md-12">
        <h1>Dropbox</h1>
        <h3>Neues Dropbox-Account</h3>
        <p>Verbinden Sie diese Anwendung mit Ihrer Dropbox, um Dateien auszutauschen:</p>
        <ol>
            <li>
                Geben Sie den Dropbox-Ordner "Apps &gt; KOFUS" für diese Anwendung frei, indem Sie auf folgenden Link klicken:<br>
                <a target="_blank" href="<?php echo $this->uriDropbox ?>">
                    <?php echo $this->uriDropbox ?>                
                </a>
            </li>
            <li>
                Kopieren Sie den Freischalt-Code von Dropbox in folgendes Formular:<br> 
                <a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'add', 'id' => 'DROPACC')) ?>">
                    Dropbox-Konto hinzufügen
                </a>
            </li>
            <li>
                Synchronisieren Sie die Dateien in Ihrem Dropbox-Ordner mit diesem System:<br>
                <a href="">Jetzt synchronisieren</a>
            </li>
        </ol>
        
        <?php if ($this->accounts) : ?>
            <h3>Aktuell verbundene Dropbox-Accounts</h3>
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-hover">
                        <tbody class="rowlink" data-link="row">
                            <?php foreach ($this->accounts as $account) : ?>
                                <tr>
                                    <td>
                                        <a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'edit', 'id' => $account->getNodeId())) ?>">
                                            <?php echo $this->escapeHtml($account->getTitle()) ?>
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach ?>
                        </tbody>
                    </table>
                </div>
            </div>
        <?php else : ?>
            <p><?php echo $this->translate('No entries.') ?></p>
        <?php endif ?>
    </div>
</div>