<h1>Dropbox</h1>
<?php if ($this->entries) : ?>
    <table class="table ____table-hover">
        <tbody >
            <?php foreach ($this->entries as $entry) : ?>
                <?php 
                    $glyphicon = null;
                    if (! $glyphicon && isset($entry['media_info']['metadata']['.tag']) && 'photo' == $entry['media_info']['metadata']['.tag'])
                        $glyphicon = 'picture';
    
                    if (! $glyphicon && $entry['.tag'] == 'folder')
                        $glyphicon = 'folder-open';
    
                    if (! $glyphicon && $entry['.tag'] == 'file')
                        $glyphicon = 'file';
                ?>
                <tr>
                    <td>
                        <?php 
                            if ($glyphicon)
                                echo '<span class="glyphicon glyphicon-' . $glyphicon . '"></span>';
                        ?>
                    </td>
                    <td>
                        <?php echo $this->escapeHtml($entry['path_display'])  ?>
                    </td>
                    <td>
                        <?php echo $this->escapeHtml($entry['id']) ?>
                    </td>
                    <td>
                    <?php if ('folder-open' == $glyphicon) : ?>
                        <a href="<?php echo $this->url('kofus_dropbox', array('controller' => 'browser', 'action' => 'index', 'id' => urlencode($entry['path_lower']))) ?>">
                            <span class="glyphicon glyphicon-arrow-right"></span>
                        </a>
                    <?php else : ?>
                        <a href="<?php echo $this->url('kofus_dropbox', array('controller' => 'browser', 'action' => 'download', 'id' => urlencode($entry['id']))) ?>">
                            <span class="glyphicon glyphicon-save" title="Download"></span>
                        </a>     
                    <?php endif ?>
                    </td>
                    
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
<?php else : ?>
    <p><?php echo $this->translate('No entries.') ?></p>
<?php endif ?>
